#!/usr/bin/env python3
"""The build-time generator batch 2's SML FFI amendment (A2) said would take
a day: derive `llama_model_params`, `llama_context_params` and `llama_batch`
layouts from the REAL pinned `llama.h`, and prove drift is a compile
failure rather than a silent corruption.

Pipeline, all driven from the field manifest in `fields.py`:

  1. Render a tiny C probe that `#include`s the pinned header and prints
     every field's `offsetof`/`sizeof`, plus each struct's total `sizeof`.
     Compile it with the system `cc` and run it — this is "reading the real
     header": nothing here is asserted, only measured.
  2. Write the measurements to `generated/offsets.json`, for `cross_check.py`
     to compare against `ctypes`.
  3. Render `generated/offsets_check.c`: the SAME measured numbers, this
     time as `_Static_assert`s checked against `offsetof`/`sizeof` of the
     header at compile time. Compiling it now is definitionally a pass (the
     numbers just came from this same header); the point of the artifact is
     that it stays in the tree and gets recompiled on every future build —
     if the pinned llama.cpp revision ever bumps and a field moves, THIS
     file fails to compile. That is the drift check.
  4. Render `generated/llama_ffi_generated.sml`: offset/size constants and
     typed accessor functions over `MLton.Pointer.t` for the three structs,
     plus `_import` declarations for the entry points whose C signature is
     scalar-only (see fields.py:STRUCT_VALUE_ENTRY_POINTS for the ones that
     are not, and why).

Usage: `python3 generate.py [--llama-root DIR] [--out-dir DIR]`
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from fields import ENTRY_POINTS, KIND_WIDTH, STRUCT_VALUE_ENTRY_POINTS, STRUCTS

HERE = Path(__file__).resolve().parent
DEFAULT_LLAMA_ROOT = Path.home() / "loom-tools/llama.cpp"
DEFAULT_OUT_DIR = HERE / "generated"


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Derive llama.cpp struct layouts from the real pinned header.")
    parser.add_argument("--llama-root", type=Path, default=DEFAULT_LLAMA_ROOT,
                         help=f"pinned llama.cpp checkout (default: {DEFAULT_LLAMA_ROOT})")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR,
                         help=f"where to write generated artifacts (default: {DEFAULT_OUT_DIR})")
    parser.add_argument("--cc", default="cc", help="C compiler to use (default: cc)")
    return parser.parse_args(argv)


# --------------------------------------------------------------------------
# Step 1-2: measure, by compiling and running a probe against the real header
# --------------------------------------------------------------------------

def render_probe_c() -> str:
    lines = [
        "// Generated by tools/ffi-spike/generate.py. Not checked in as a",
        "// build artifact; regenerate with `task ffi-spike`.",
        "#include <stdio.h>",
        "#include <stddef.h>",
        '#include "llama.h"',
        "",
        "int main(void) {",
    ]
    for struct_name, spec in STRUCTS.items():
        ctype = spec["ctype"]
        for field_name, _kind in spec["fields"]:
            lines.append(
                f'    printf("FIELD\\t{struct_name}\\t{field_name}\\t%zu\\t%zu\\n", '
                f"offsetof({ctype}, {field_name}), "
                f"sizeof((({ctype}*)0)->{field_name}));")
        lines.append(f'    printf("STRUCT\\t{struct_name}\\t%zu\\n", sizeof({ctype}));')
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def compile_and_run(cc: str, source: str, includes: list[Path], workdir: Path,
                     basename: str, *, run: bool) -> tuple[str, float]:
    """Compile `source` (written as `<basename>.c`) with `cc`. Runs it and
    returns (captured stdout, wall-clock seconds) if `run`, else compiles
    with `-c` only and returns ("", seconds)."""
    import time
    src_path = workdir / f"{basename}.c"
    src_path.write_text(source)
    cmd = [cc, "-std=gnu11", "-Wall"]
    for inc in includes:
        cmd += ["-I", str(inc)]
    started = time.monotonic()
    if run:
        out_path = workdir / basename
        cmd += ["-o", str(out_path), str(src_path)]
        subprocess.run(cmd, check=True)
        result = subprocess.run([str(out_path)], check=True, capture_output=True, text=True)
        elapsed = time.monotonic() - started
        return result.stdout, elapsed
    else:
        cmd += ["-c", "-o", str(workdir / f"{basename}.o"), str(src_path)]
        subprocess.run(cmd, check=True)
        elapsed = time.monotonic() - started
        return "", elapsed


def parse_probe_output(text: str) -> dict:
    measured: dict[str, dict] = {name: {"fields": {}} for name in STRUCTS}
    for line in text.splitlines():
        parts = line.split("\t")
        if parts[0] == "FIELD":
            _, struct_name, field_name, offset, size = parts
            measured[struct_name]["fields"][field_name] = {
                "offset": int(offset), "size": int(size)}
        elif parts[0] == "STRUCT":
            _, struct_name, total = parts
            measured[struct_name]["sizeof"] = int(total)
    for struct_name, spec in STRUCTS.items():
        got = set(measured[struct_name]["fields"])
        want = {f for f, _ in spec["fields"]}
        if got != want:
            raise RuntimeError(
                f"{struct_name}: probe measured fields {sorted(got)} but "
                f"fields.py declares {sorted(want)} — the header and the "
                "manifest have drifted apart; this IS the check working")
    return measured


# --------------------------------------------------------------------------
# Step 3: the static_assert drift gate
# --------------------------------------------------------------------------

def render_offsets_check_c(measured: dict) -> str:
    lines = [
        "// Generated by tools/ffi-spike/generate.py from measurements taken",
        "// against the pinned llama.cpp revision recorded in offsets.json.",
        "//",
        "// This file is the drift check: it is NOT re-derived at every",
        "// build, it PINS the numbers measured once. Recompiling it against",
        "// a future llama.h is what catches a field moving, being resized,",
        "// or disappearing -- as a compile failure, not a corrupted struct.",
        "#include <stddef.h>",
        '#include "llama.h"',
        "",
    ]
    for struct_name, spec in STRUCTS.items():
        ctype = spec["ctype"]
        m = measured[struct_name]
        lines.append(f"// -- {struct_name} --")
        for field_name, _kind in spec["fields"]:
            f = m["fields"][field_name]
            lines.append(
                f'_Static_assert(offsetof({ctype}, {field_name}) == {f["offset"]}, '
                f'"{struct_name}.{field_name} moved");')
            lines.append(
                f'_Static_assert(sizeof((({ctype}*)0)->{field_name}) == {f["size"]}, '
                f'"{struct_name}.{field_name} changed size");')
        lines.append(
            f'_Static_assert(sizeof({ctype}) == {m["sizeof"]}, '
            f'"sizeof({struct_name}) changed");')
        lines.append("")
    lines.append("int main(void) { return 0; }")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Step 4: the generated SML
# --------------------------------------------------------------------------

_SML_ACCESSOR = {
    # kind -> (MLton.Pointer get, MLton.Pointer set, SML type, C width)
    "ptr": ("getPointer", "setPointer", "MLton.Pointer.t"),
    "i32": ("getInt32", "setInt32", "Int32.int"),
    "u32": ("getWord32", "setWord32", "Word32.word"),
    "f32": ("getReal32", "setReal32", "Real32.real"),
    "size_t": ("getWord64", "setWord64", "Word64.word"),
}

_SML_IMPORT_TYPE = {
    "ptr": "MLton.Pointer.t", "i32": "Int32.int", "u32": "Word32.word",
    "str": "string", "unit": "unit",
}


def sml_field_name(name: str) -> str:
    """snake_case -> camelCase, SML's field-naming convention."""
    head, *rest = name.split("_")
    return head + "".join(w.capitalize() for w in rest)


def render_struct_sml(struct_name: str, spec: dict, measured: dict) -> str:
    ctype = spec["ctype"]
    m = measured[struct_name]
    sml_name = "".join(w.capitalize() for w in struct_name.split("_"))
    lines = [f"  (* {ctype}, sizeof = {m['sizeof']} bytes, measured against the"]
    lines.append(f"     pinned llama.h *)")
    lines.append(f"  structure {sml_name} = struct")
    lines.append(f"    val size : word = 0w{m['sizeof']}")
    lines.append("")
    for field_name, kind in spec["fields"]:
        f = m["fields"][field_name]
        offset, width = f["offset"], KIND_WIDTH[kind]
        camel = sml_field_name(field_name)
        if kind == "bool":
            # C `_Bool` is 1 byte; MLton's FFI `bool` marshals as C int32_t
            # (see ForeignFunctionInterfaceTypes) so it is wrong for a
            # struct FIELD, which is raw memory, not a `_import` argument.
            # Word8 peek/poke plus an explicit ML-side bool conversion is
            # the correct match for a 1-byte in-memory field.
            lines.append(f"    (* {field_name}: bool, offset {offset}, 1 byte *)")
            lines.append(
                f"    fun get{camel[0].upper()}{camel[1:]} (p : MLton.Pointer.t) : bool =")
            lines.append(f"      MLton.Pointer.getWord8 (p, {offset}) <> 0w0")
            lines.append(
                f"    fun set{camel[0].upper()}{camel[1:]} "
                f"(p : MLton.Pointer.t, v : bool) : unit =")
            lines.append(
                f"      MLton.Pointer.setWord8 (p, {offset}, if v then 0w1 else 0w0)")
        else:
            getter, setter, smlty = _SML_ACCESSOR[kind]
            if offset % width != 0:
                raise RuntimeError(
                    f"{struct_name}.{field_name}: measured offset {offset} is not "
                    f"{width}-aligned -- MLton.Pointer's element-index addressing "
                    "cannot express this without a byte-level fallback; the manifest "
                    "or the header has an unexpected packing")
            index = offset // width
            lines.append(f"    (* {field_name}: {kind}, offset {offset}, index {index} *)")
            lines.append(
                f"    fun get{camel[0].upper()}{camel[1:]} (p : MLton.Pointer.t) : {smlty} =")
            lines.append(f"      MLton.Pointer.{getter} (p, {index})")
            lines.append(
                f"    fun set{camel[0].upper()}{camel[1:]} "
                f"(p : MLton.Pointer.t, v : {smlty}) : unit =")
            lines.append(f"      MLton.Pointer.{setter} (p, {index}, v)")
        lines.append("")
    lines.append("  end")
    return "\n".join(lines)


def render_sml(measured: dict, revision: str) -> str:
    lines = [
        "(* Generated by tools/ffi-spike/generate.py -- DO NOT EDIT BY HAND.",
        f"   Source of truth: {revision}'s include/llama.h, measured via a",
        "   compiled-and-run C probe (see offsets_check.c for the pinned",
        "   static_assert drift gate over the same numbers).",
        "",
        "   Two different things live in this file:",
        "     - offset/size constants + typed accessor functions over a raw",
        "       MLton.Pointer.t, for the three structs the Python ctypes shim",
        "       mirrors (llama_model_params, llama_context_params, llama_batch).",
        "     - `_import` declarations, MLton FFI style, for the entry points",
        "       whose C signature is scalar-only.",
        "",
        "   NOT attempted here: llama_model_default_params, llama_context_default_params,",
        "   llama_model_load_from_file, llama_init_from_model, llama_batch_get_one and",
        "   llama_decode all pass or return one of the three structs BY VALUE, and",
        "   MLton's `_import` has no struct-by-value marshalling (only",
        "   bool/char/int/real/word/MLton.Pointer.t and arrays/vectors thereof cross the",
        "   _import boundary -- see ForeignFunctionInterfaceTypes). A real binding would",
        "   need a small generated C shim taking/returning these by pointer instead; that",
        "   shim is itself generatable from the same manifest, but writing it was judged",
        "   out of scope for a one-day spike. llama_log_set takes a C function pointer",
        "   and would need `_export`, also not attempted. *)",
        "",
        "structure LlamaFFI = struct",
        "",
    ]
    for struct_name, spec in STRUCTS.items():
        lines.append(render_struct_sml(struct_name, spec, measured))
        lines.append("")

    lines.append("  (* -- _import declarations: scalar-only entry points -- *)")
    lines.append("  structure Raw = struct")
    for c_name, arg_kinds, ret_kind in ENTRY_POINTS:
        args = " * ".join(_SML_IMPORT_TYPE[k] for k in arg_kinds) if arg_kinds else "unit"
        ret = _SML_IMPORT_TYPE[ret_kind]
        lines.append(f'    val {c_name} = _import "{c_name}" : {args} -> {ret};')
    lines.append("  end")
    lines.append("")
    lines.append("end")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------

def main(argv=None) -> int:
    args = parse_args(argv)
    llama_root = args.llama_root.expanduser()
    include_dirs = [llama_root / "include", llama_root / "ggml" / "include"]
    for inc in include_dirs:
        if not inc.is_dir():
            print(f"error: expected include dir not found: {inc}", file=sys.stderr)
            return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)

    revision = "llama.cpp (revision unknown -- .git not read by this generator)"
    git_head = llama_root / ".git" / "HEAD"
    if git_head.is_file():
        head = git_head.read_text().strip()
        if head.startswith("ref:"):
            # On a branch: HEAD points at refs/heads/<name>, resolve that.
            ref_path = llama_root / ".git" / head.split(":", 1)[1].strip()
            sha = ref_path.read_text().strip() if ref_path.is_file() else head
        else:
            # Detached HEAD (the normal state for a pinned checkout): the
            # full SHA is right there, and must NOT be shadowed by a stale
            # refs/heads/<branch> that happens to exist in the same clone.
            sha = head
        revision = f"llama.cpp @ {sha[:12]}"

    with tempfile.TemporaryDirectory(prefix="ffi-spike-") as tmp:
        workdir = Path(tmp)

        probe_c = render_probe_c()
        (args.out_dir / "probe.c").write_text(probe_c)
        stdout, probe_seconds = compile_and_run(
            args.cc, probe_c, include_dirs, workdir, "probe", run=True)
        measured = parse_probe_output(stdout)
        print(f"[1/3] measured {sum(len(s['fields']) for s in measured.values())} "
              f"fields across {len(measured)} structs in {probe_seconds:.2f}s "
              "(compile + run the probe)")

        offsets_path = args.out_dir / "offsets.json"
        offsets_path.write_text(json.dumps(
            {"llama_cpp_revision": revision, "structs": measured}, indent=2) + "\n")
        print(f"      wrote {offsets_path}")

        check_c = render_offsets_check_c(measured)
        check_path = args.out_dir / "offsets_check.c"
        check_path.write_text(check_c)
        _, check_seconds = compile_and_run(
            args.cc, check_c, include_dirs, workdir, "offsets_check", run=False)
        print(f"[2/3] offsets_check.c compiled clean in {check_seconds:.2f}s "
              "-- static_assert drift gate is live")

        sml = render_sml(measured, revision)
        sml_path = args.out_dir / "llama_ffi_generated.sml"
        sml_path.write_text(sml)
        print(f"[3/3] wrote {sml_path} "
              f"({len(measured)} struct accessor blocks, {len(ENTRY_POINTS)} _import decls, "
              f"{len(STRUCT_VALUE_ENTRY_POINTS)} entry points intentionally NOT imported)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
